# Generated by Django 3.1.5 on 2021-03-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='fileUpload',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
