# Generated by Django 3.1.5 on 2021-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopage', '0004_auto_20210301_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='fileUpload',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
